name: update-flake-lock
on:
  workflow_dispatch:

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - name: Update flake.lock
        uses: e1mo/update-flake-lock-gc-action@main
        with:
          check-command: |
            nix build .\#pkgs.x86_64-linux.hello --print-out-paths -L --no-update-lock-file
